channels:
    - conda-forge
name:
    bio-voxel_tests
dependencies:
    - pandas
    - dash
    - plotly
    - pip
    - scikit-images
    - python-elf
    - numpy
    - trimesh
    -pip:
        - elf
        - skan